name: "tests"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - php7.4
          - php8.0
    steps:
      - uses: actions/checkout@v1
      - name: "Cache dependencies installed with composer"
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: php${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            php${{ matrix.php-version }}-composer-
      - name: "Validate composer.json file"
        run: composer validate
      - name: "Install PHP coding style checker"
        run: composer require "squizlabs/php_codesniffer":"^3.0"
      - name: "Check coding style after PSR-12 standard"
        run: php ./vendor/bin/phpcs --standard=PSR12 --encoding=utf-8 -n ./src
